# fly.toml app configuration file generated for cinder-server2 on 2023-11-18T12:56:22-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cinder-server2"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
